name: Build C Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Step 3: List repository files for debugging
      - name: List repository structure
        run: ls -R

      # Step 4: Build the project
      - name: Build project
        run: |
          cd Uartronica_Control_Board/Debug
          make

      # Optional Step 5: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: Uartronica_Control_Board/Debug